name: Deploy Metabase
run-name: Deploy ${{ github.ref_name }} to Metabase ${{ inputs.environment || (github.event_name == 'release' && 'prod') || 'nonprod'}}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - training
          - prod
      image-tag:
        description: "Metabase enterprise image tag to deploy"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-metabase.yml
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        envs: ${{ fromJSON(format('["{0}"]', inputs.environment))  }}
    with:
      app_name: "metabase"
      version: ${{ inputs.image-tag }}
      environment: ${{ matrix.envs }}

  send-slack-notification:
    if: failure() && (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release')
    needs: [deploy]
    uses: ./.github/workflows/send-slack-notification.yml
    secrets: inherit
