name: CI Infra Service Checks - 

on:
  # !! Once you've set up the dev environment and are ready to enable automated
  # infra tests, run:
  #
  # nava-platform infra update --answers-only --data app_has_dev_env_setup=true .
  #
  # to enable these lines. They are here as comments for context.
  #
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - infra//service/**
  #     - infra/modules/**
  #     - infra/test/**
  #     - .github/workflows/ci--infra-service.yml
  # pull_request:
  #   paths:
  #     - infra//service/**
  #     - infra/modules/**
  #     - infra/test/**
  #     - .github/workflows/ci--infra-service.yml
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "main"
        description: Tag or branch or SHA to test

jobs:
  build-and-publish:
    name: Build
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: 
      ref: ${{ inputs.version || github.ref }}

  infra-test-e2e:
    name: Test service
    runs-on: ubuntu-latest
    needs: [build-and-publish]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version || github.ref }}

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - uses: actions/setup-go@v5
        with:
          go-version-file: "infra/test/go.mod"

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: 
          # Run infra CI on dev environment
          environment: dev

      - name: Run Terratest
        run: make infra-test-service APP_NAME=
