name: CI Documentation Checks

on:
  schedule:
    # Run weekly on Monday at 9:00 AM EST
    - cron: "0 14 * * 1"
  workflow_dispatch:

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This is the GitHub Actions-friendly port of the linter used in the Makefile.
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--quiet --config ./.github/workflows/lychee.toml ."
          fail: true
