<<<<<<< before updating
# GitHub Actions CI workflow that runs vulnerability scans on the application's Docker image
# to ensure images built are secure before they are deployed.

name: CI Frontend Vulnerability Scans

on:
=======
name: CI Vulnerability Scans - frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-frontend-vulnerability-scans.yml
>>>>>>> after updating
  pull_request:
    paths:
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-frontend-vulnerability-scans.yml
      - .github/workflows/vulnerability-scans.yml
      - frontend/Dockerfile
      - frontend/package.json
      - frontend/package-lock.json

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: "frontend"
