name: CI Infra Service Checks - frontend

on:
  push:
    branches:
      - main
    paths:
      - infra/frontend/service/**
      - infra/modules/**
      - infra/test/**
      - .github/workflows/ci-frontend-infra-service.yml
  pull_request:
    paths:
      - infra/frontend/service/**
      - infra/modules/**
      - infra/test/**
      - .github/workflows/ci-frontend-infra-service.yml
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "main"
        description: Tag or branch or SHA to test

jobs:
  build-and-publish:
    name: Build
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: frontend
      ref: ${{ inputs.version || github.ref }}

  infra-test-e2e:
    name: Test service
    runs-on: ubuntu-latest
    needs: [build-and-publish]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version || github.ref }}

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - uses: actions/setup-go@v5
        with:
          go-version-file: "infra/test/go.mod"

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: frontend
          # Run infra CI on dev environment
          environment: dev

      - name: Run Terratest
        run: make infra-test-service APP_NAME=frontend
