name: CI Vulnerability Scans

on:
  push:
    branches:
      - main
    paths:
      - nofos/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/ci-nofos-vulnerability-scans.yml
  pull_request:
    paths:
      - nofos/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/ci-nofos-vulnerability-scans.yml

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: nofos
