name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "the name of the application environment (e.g. dev, staging, prod)"
        required: true
        type: string
      version:
        description: "git reference to deploy (e.g., a branch, tag, or commit SHA)"
        required: true
        type: string

concurrency: cd-nofos-${{ inputs.environment }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Restore NOFOs commit hash
        uses: actions/cache/restore@v4
        with:
          path: /tmp/commit-hash.txt
          key: nofos-docker-image-${{ github.sha }}

      - name: Restore cached Docker image
        uses: actions/cache/restore@v4
        with:
          path: /tmp/docker-image.tar
          key: nofos-docker-image-${{ github.sha }}

      - name: Load cached Docker image
        run: docker load < /tmp/docker-image.tar

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: nofos
          environment: ${{ inputs.environment }}

      - name: Publish release
        run: make release-publish APP_NAME=nofos IMAGE_TAG=$(cat /tmp/commit-hash.txt)

      - name: Deploy release
        run: make release-deploy APP_NAME=nofos ENVIRONMENT=${{ inputs.environment }} IMAGE_TAG=$(cat /tmp/commit-hash.txt)
