name: Slack Notification

on:
  workflow_call:
  workflow_dispatch:

jobs:
  send-slack-notification:
    name: Send Slack notification on failure
    runs-on: ubuntu-22.04
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.ALERTS_SLACK_BOT_TOKEN }}" \
          -H "Content-Type: application/json; charset=utf-8" \
          --data '{
            "channel": "${{ secrets.SLACK_ALERTS_CHANNEL_ID }}",
            "text": ":x: *GitHub Actions Failure Alert*",
            "attachments": [
            {
              "color": "#ff0000",
              "title": "Workflow *'"${{ github.workflow }}"'* failed",
              "fields": [
              {
                "title": "Run By",
                "value": "'"${{ github.triggering_actor }}"'"
              },
              {
                "title": "Event Name",
                "value": "'"${{ github.event_name }}"'"
              },
              {
                "title": "Ref Type",
                "value": "'"${{ github.ref_type }}"'"
              },
              {
                "title": "Ref Name",
                "value": "'"${{ github.ref_name }}"'"
              },
              {
                "title": "Workflow URL",
                "value": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
              }
              ],
              "footer": "GitHub Actions",
              "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "ts": '$(date +%s)'
            }
            ]
          }' https://slack.com/api/chat.postMessage
