name: Slack Notification

on:
  workflow_call:
  workflow_dispatch:

jobs:
  send-slack-notification:
    name: Send Slack notification on failure
    runs-on: ubuntu-22.04
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.ALERTS_SLACK_BOT_TOKEN }}" \
          -H "Content-Type: application/json; charset=utf-8" \
          --data '{
            "channel": "${{ secrets.SLACK_ALERTS_CHANNEL_ID }}",
            "text": ":x: *GitHub Actions Failure Alert*",
            "attachments": [
              {
                "color": "#ff0000",
                "title": "Workflow *'"${{ github.workflow }}"'* failed",
                "blocks": [
                	{
                    "type": "table",
                    "rows": [
                      [
                        {
                          "type": "rich_text",
                          "elements": [
                            {
                              "type": "rich_text_section",
                              "elements": [
                                {
                                  "type": "text",
                                  "text": "Run By",
                                  "style": {
                                    "bold": true
                                  }
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "type": "rich_text",
                          "elements": [
                            {
                              "type": "rich_text_section",
                              "elements": [
                                {
                                  "type": "text",
                                  "text": "'"${{ github.triggering_actor }}"'"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    ]
                  }
                ]
              }
            ]
          }' https://slack.com/api/chat.postMessage
